Fix the pages being out of order
UB-Mannheim/zotero-ocr pull request #77
Opened 2024-06-19 17:02 UTC by callisto-jovy

This resolves #76. 

Instead of iterating over the contents of the directory and inserting them based on a matched predicate, we count the number of matched entries and generate the paths ourselves.

2024-06-19 17:03 UTC, callisto-jovy commented
I'm not an experienced JavaScript developer, feel free to make changes.

2024-07-03 19:36 UTC, stweil requested changes
A lot of the changes in this pull request simply reformat the code. Would you mind changing your PR and keep the original lines and style?

Maybe you can also just use the code from Zotero 6 to fix the issue.

Both suggested changes would make the review easier.

2024-07-04 18:10 UTC, callisto-jovy commented
Does this now look better @stweil?

2024-07-08 04:13 UTC, aborel commented
Sorry about my lack of reactivity, I have been unable to read the proposed code until yesterday.
Thanks a lot for reporting the bug, and thanks for the PR! However, I don't think it is evolving in the right direction.

The first commit would have been easier to review without the style changes. In the 2nd one, I don't think returning to Zotero6-compatible code is the way to go.

I have a much simpler fix in mind: since imageListArray is not guaranteed to be in the right order, sorting it before writing imagelist.txt should do the trick. I will push the commit in a minute, but it is best if @stweil or @zuphilip publishes the new version.

2024-07-08 15:08 UTC, stweil commented
Thanks again for your bug report and your efforts with this pull request. Meanwhile a different fix was applied and released in release 0.7.3, so this one here is no longer needed.

2024-07-08 15:08 UTC, closed without merging